# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3bd62cb52a4bb992f5060524819f7a55318e630a587e7d141498902a03c0fb2b49ab9f17db1369f4f608c070e83406a69a0031150c39c78d58a222825eb70847

test:
  secret_key_base: f5705f78adc83790f54e08f35f7f090bffa0f76efdec89e0d3e7a896751a4ef94363f453ff0a5463a4903ec7b5c8e143c7b5f62c077368b8f0e9b8787f085ee3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
